CREATE TABLE `opening_balance` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IN_BANK_ACCOUNT` decimal(15,2) DEFAULT NULL,
  `CASH_IN_HAND` decimal(15,2) DEFAULT NULL,
  `SESSION_ID` int(11) DEFAULT NULL,
  `APARTMENT_ID` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8mb4;

CREATE TABLE account_transaction (
  ID int(11) NOT NULL AUTO_INCREMENT,
  TYPE varchar(45) DEFAULT NULL,
  REF_NO varchar(45) DEFAULT NULL,
  AMOUNT decimal(15,2) DEFAULT NULL,
  REMARKS varchar(190) DEFAULT NULL,
  TRANS_DATE date DEFAULT NULL,
  SESSION_ID int(11) DEFAULT NULL,
  APARTMENT_ID int(11) DEFAULT NULL,
  CREATED_BY int(11) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8mb4;

ALTER TABLE user_details ADD COLUMN TYPE VARCHAR(45) NULL DEFAULT NULL AFTER ID,
ADD COLUMN ROLE VARCHAR(45) NULL DEFAULT NULL AFTER TYPE;

CREATE TABLE `user_role_permission` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OBJECT` varchar(45) NOT NULL,
  `ROLE` varchar(45) NOT NULL,
  `CREATE_PERM` tinyint(1) DEFAULT '0',
  `VIEW_PERM` tinyint(1) DEFAULT '0',
  `EDIT_PERM` tinyint(1) DEFAULT '0',
  `DELETE_PERM` tinyint(1) DEFAULT '0',
  `APARTMENT_ID` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
